#端口
server:
  port: 1009

#服务名称
spring:
  application:
    name: service-gateway
  #nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#    sentinel:
#      transport:
#        dashboard: localhost:8333
#        port: 8719

    #服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      #设置路由
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/user/**

  zipkin:
    base-url: http://192.168.0.169:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0  #采样的百分比

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          sleuth: DEBUG
          openfeign: DEBUG
        web:
          servlet:
            DispatcherServlet: DEBUG

