server:
  port: 1001

spring:
  #mysq连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.169:3306/mytest?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456

  cloud:
    nacos:
      # 注册中心
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yml

  zipkin:
    base-url: http://192.168.0.169:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0  #采样的百分比

logging:
    level:
      root: INFO
      org:
        springframework:
          cloud:
            sleuth: DEBUG
            openfeign: DEBUG
          web:
            servlet:
              DispatcherServlet: DEBUG

#    sentinel:
#      transport:
#        dashboard: localhost:8333
#        port: 8719

#feign:
#  sentinel:
#    enabled: true